### PR TITLE
Added Gray Hat Python

### PR DESCRIPTION
**Pull request by sygthred**
Added under "Programming Languages"

### CODE REVIEW

**Review by 0xbadshah — APPROVED** [review]

**Comment by 0xbadshah** [comment]
Thanks for the PR !

**Comment by helgaloans** [comment]
Remove this before I take legal actions


Sent from Yahoo Mail for iPhone


On Sunday, January 20, 2019, 3:21 AM, Chandrapal <notifications@github.com> wrote:


Thanks for the PR !

**Comment by 0xbadshah** [comment]
Hey @helgaloans 

Here's the readme for you:

**Disclaimer: The contributor(s) cannot be held responsible for any misuse of the data. This repository is just a collection of URLs to download eBooks for free. Download the eBooks at your own risks.
DMCA takedown cannot be possible as we are not republishing the books/infringement of code, but we are just hosting the links to 3rd party websites where these books can be downloaded.**
 
I am not hosting the ebook. I have merged a PR that contains a link to the ebook. If you are interested in taking legal action, please contact Google to remove the link from drive.

If you want to remove it from the repo, please remove the link and create a PR, I will merge it.

**Comment by 0xbadshah** [comment]
Hey @helgaloans the book link didnt make it to the list at all. It was deleted when merging other PRs.

**Pull request merged**
